sudo: required

services:
  - docker
env:
  - IMAGE_NAME=msvrtan/code
script:
  - if [ $TRAVIS_TAG ]; then
    docker build -t $IMAGE_NAME:$TRAVIS_TAG  .;
    fi
  - if [ -z $TRAVIS_TAG ]; then
    docker build .;
    fi

after_success:
  - docker login -u="$REGISTRY_USER" -p="$REGISTRY_PASS"
  - if [ "$TRAVIS_TAG" ]; then docker push $IMAGE_NAME:$TRAVIS_TAG; fi
  - docker logout

  